obras_particulares/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^persona/', include('persona.urls')),
    url(r'^tipos/', include('tipos.urls')),
    url(r'^tramite/', include('tramite.urls')),
    url(r'^documento/', include('documento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

persona/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from . import views
from tramite.models import *
from persona.views import *


urlpatterns = [

    #No me acuerdo de donde son - Acomodar esto!!!! -------------------------------------------------------------------

    url(r'^altapersona$', views.alta_persona, name="alta_persona"),
    url(r'^crearusuario/(?P<pk_persona>\d+)/$', views.crear_usuario, name="crear_usuario"),
    url(r'^aceptar_tramite/(?P<pk_tramite>\d+)/$', views.aceptar_tramite, name="aceptar_tramite"),

    # propietario ---------------------------------------------------------------------------------------------------
    url(r'^propietario$', views.mostrar_propietario, name="propietario"),
    url(r'^ver_historial_tramite/(?P<pk_tramite>\d+)/$', views.ver_historial_tramite, name="ver_historial_tramite"),
    url(r'^solicitud_final_obra_propietario/(?P<pk_tramite>\d+)/$', views.propietario_solicita_final_obra, name="propietario_solicita_final_obra"),
    url(r'^documentos_de_estado/(?P<pk_estado>\d+)/$', views.documentos_de_estado, name="documentos_de_estado"),
    url(r'^cargar_aprobacion_propietario/(?P<pk_tramite>\d+)/$', views.cargar_aprobacion_propietario, name="cargar_aprobacion_propietario"),
    url(r'^cargar_final_de_obra_total_propietario/(?P<pk_tramite>\d+)/$', views.cargar_final_de_obra_total_propietario, name="cargar_final_de_obra_total_propietario"),
    url(r'^cambiar_profesional_de_tramite/(?P<pk_tramite>\d+)/$', views.cambiar_profesional_de_tramite, name="cambiar_profesional_de_tramite"),

    # profesional ---------------------------------------------------------------------------------------------------
    url(r'^profesional$', views.mostrar_profesional, name="profesional"),
    url(r'^ver_documentos_tramite_profesional/(?P<pk_tramite>\d+)/$', views.ver_documentos_tramite_profesional, name="ver_documentos_tramite_profesional"),
    url(r'^ver_documentos_corregidos/(?P<pk_tramite>\d+)/$', views.ver_documentos_corregidos, name="ver_documentos_corregidos"),
    url(r'^solicitud_final_obra/(?P<pk_tramite>\d+)/$', views.profesional_solicita_final_obra, name="profesional_solicita_final_obra"),
    url(r'^solicitud_no_final_obra/(?P<pk_tramite>\d+)/$', views.profesional_solicita_no_final_obra, name="profesional_solicita_no_final_obra"),
    url(r'^solicitud_final_obra_parcial/(?P<pk_tramite>\d+)/$', views.profesional_solicita_final_obra_parcial,name="profesional_solicita_final_obra_parcial"),
    url(r'^profesional_solicita_aprobar_tramite/(?P<pk_tramite>\d+)/$', views.profesional_solicita_aprobar_tramite, name="profesional_solicita_aprobar_tramite"),
    url(r'^profesional_solicita_no_aprobar_tramite/(?P<pk_tramite>\d+)/$', views.profesional_solicita_no_aprobar_tramite,name="profesional_solicita_no_aprobar_tramite"),
    url(r'^enviar_correcciones/(?P<pk_tramite>\d+)/$', views.enviar_correcciones, name="enviar_correcciones"),
    url(r'^profesional/estado_tramite$', views.listado_tramites_de_profesional, name="estado_tramite"),
    url(r'^documento_de_estado/(?P<pk_estado>\d+)/$', views.documento_de_estado, name="documento_de_estado"),
    url(r'^cargar_final_de_obra_total_profesional/(?P<pk_tramite>\d+)/$', views.cargar_final_de_obra_total_profesional, name="cargar_final_de_obra_total_profesional"),
    url(r'^cargar_no_final_de_obra_total_profesional/(?P<pk_tramite>\d+)/$', views.cargar_no_final_de_obra_total_profesional, name="cargar_no_final_de_obra_total_profesional"),
    url(r'^cargar_no_aprobar_profesional/(?P<pk_tramite>\d+)/$', views.cargar_no_aprobar_profesional, name="cargar_no_aprobar_profesional"),

    # administrativo ------------------------------------------------------------------------------------------------
    url(r'^administrativo$', views.mostrar_administrativo, name="administrativo"),
    url(r'^crearusuario/(?P<pk_propietario>\d+)/$', views.crear_usuario, name="crear_usuario"),
    url(r'^administrativo/tramite_listar$', views.listado_de_tramites_iniciados, name="tramite_listar"),
    url(r'^ver_un_certificado/(?P<pk_persona>\d+)/$', views.ver_un_certificado, name="ver_un_certificado"),
    url(r'^documentos_tramite_administrativo/(?P<pk_tramite>\d+)/$', views.ver_documentos_tramite_administrativo, name="ver_documentos_tramite_administrativo"),
    url(r'^rechazar_tramite/(?P<pk_tramite>\d+)/$', views.rechazar_tramite, name="rechazar_tramite"),
    url(r'^aceptar_tramite/(?P<pk_tramite>\d+)/$', views.aceptar_tramite, name="aceptar_tramite"),
    url(r'^aprobar_tramite/(?P<pk_tramite>\d+)/$', views.aprobar_tramite, name="aprobar_tramite"),
    url(r'^no_aprobar_tramite/(?P<pk_tramite>\d+)/$', views.no_aprobar_tramite, name="no_aprobar_tramite"),
    url(r'^cargar_aprobacion/(?P<pk_tramite>\d+)/$', views.cargar_aprobacion, name="cargar_aprobacion"),
    url(r'^cargar_no_aprobacion/(?P<pk_tramite>\d+)/$', views.cargar_no_aprobacion, name="cargar_no_aprobacion"),
    url(r'^aprobar_final_de_obra/(?P<pk_tramite>\d+)/$', views.habilitar_final_obra, name="habilitar_final_obra"),
    url(r'^cargar_final_de_obra_total/(?P<pk_tramite>\d+)/$', views.cargar_final_de_obra_total,name="cargar_final_de_obra_total"),
    url(r'^dar_baja_tramite/(?P<pk_tramite>\d+)/$', views.dar_baja_tramite, name="dar_baja_tramite"),
    url(r'^administrativo/listado_profesionales/$', views.listado_profesionales_administrativo, name="listado_profesionales"),
    url(r'^reporte_profesionales_administrativo_excel/', ReporteProfesionalesAdministrativoExcel.as_view(), name="reporte_profesionales_administrativo_excel"),
    url(r'^administrativo/listado_propietarios/$', views.listado_propietarios_administrativo, name="listado_propietarios_administrativo"),
    url(r'^reporte_propietarios_administrativo_excel/', ReportePropietariosAdministrativoExcel.as_view(), name="reporte_propietarios_administrativo_excel"),
    url(r'^reporte_profesionales_administrativo_pdf/$', login_required(ReporteProfesionalesAdministrativoPdf.as_view()), name="reporte_profesionales_administrativo_pdf"),
    url(r'^reporte_propietarios_administrativo_pdf/$', login_required(ReportePropietariosAdministrativoPdf.as_view()), name="reporte_propietarios_administrativo_pdf"),

    # visador -------------------------------------------------------------------------------------------------------
    url(r'^visador$', views.mostrar_visador, name="visador"),
    url(r'^agendar_tramite_para_visado/(?P<pk_tramite>\d+)/$', views.agendar_tramite_para_visado, name="agendar_tramite_para_visado"),
    url(r'^ver_documentos_para_visado/(?P<pk_tramite>\d+)/$', views.ver_documentos_para_visado, name="ver_documentos_para_visado"),
    url(r'^aprobar_visado/(?P<pk_tramite>\d+)/$', views.aprobar_visado, name="aprobar_visado"),
    url(r'^no_aprobar_visado/(?P<pk_tramite>\d+)/$', views.no_aprobar_visado, name="no_aprobar_visado"),
    url(r'^ver_documentos_visados/(?P<pk_estado>\d+)/$', views.ver_documentos_visados, name="ver_documentos_visados"),

    # inspector -----------------------------------------------------------------------------------------------------
    url(r'^inspector$', views.mostrar_inspector, name="inspector"),
    url(r'^vista_de_inspecciones/(?P<pk_tramite>\d+)/$', views.ver_inspecciones, name="ver_inspecciones"),
    url(r'^cargar_inspeccion/(?P<pk_tramite>\d+)/$', views.cargar_inspeccion, name="cargar_inspeccion"),
    url(r'^agendar_tramite/(?P<pk_tramite>\d+)/$', views.agendar_tramite, name="agendar_tramite"),
    url(r'^rechazar_inspeccion/(?P<pk_tramite>\d+)/$', views.rechazar_inspeccion, name="rechazar_inspeccion"),
    url(r'^aceptar_inspeccion/(?P<pk_tramite>\d+)/$', views.aceptar_inspeccion, name="aceptar_inspeccion"),
    url(r'^documentos_tramite_inspector/(?P<pk_estado>\d+)/$', views.ver_documentos_tramite_inspector, name="documentos_tramite_inspector"),

    #jefeinspector --------------------------------------------------------------------------------------------------
    url(r'^jefeinspector$', views.mostrar_jefe_inspector, name="jefeinspector"),
    url(r'^cargar_inspeccion_final/(?P<pk_tramite>\d+)/$', views.cargar_inspeccion_final, name="cargar_inspeccion_final"),
    url(r'^agendar_inspeccion_final/(?P<pk_tramite>\d+)/$', views.agendar_inspeccion_final, name="agendar_inspeccion_final"),
    url(r'^aceptar_inspeccion_final/(?P<pk_tramite>\d+)/$', views.aceptar_inspeccion_final, name="aceptar_inspeccion_final"),
    url(r'^inspectores_sin_inspecciones_agendadas/(?P<pk_estado>\d+)/$', views.inspectores_sin_inspecciones_agendadas, name="inspectores_sin_inspecciones_agendadas"),
    url(r'^documentos_tramite_jefeinspector/(?P<pk_estado>\d+)/$', views.ver_documentos_tramite_jefeinspector, name="documentos_tramite_jefeinspector"),
    url(r'^documentos_tramite_inspector_por_jefeinspector/(?P<pk_estado>\d+)/$', views.ver_documentos_tramite_inspector_por_jefeinspector, name="documentos_tramite_inspector_por_jefeinspector"),

    #director -------------------------------------------------------------------------------------------------------
    url(r'^director$', views.mostrar_director, name="director"),
    url(r'^vista_de_tramites$', views.ver_listado_todos_tramites, name="vista_de_tramites"),
    url(r'^detalle_de_tramite/(?P<pk_tramite>\d+)/$', views.detalle_de_tramite, name="detalle_de_tramite"),
    url(r'^reporte_tramites_director_excel/', ReporteTramitesDirectorExcel.as_view(), name="reporte_tramites_director_excel"),
    url(r'^reporte_tramites_director_pdf/$', login_required(ReporteTramitesDirectorPdf.as_view()), name="reporte_tramites_director_pdf"),
    url(r'^vista_de_usuarios$', views.ver_listado_todos_usuarios, name="vista_de_usuarios"),
    url(r'^ver_actividad_usuario/(?P<usuario>\w+)/$', views.ver_actividad_usuario, name="ver_actividad_usuario"),
    url(r'^visadores_sin_visado_agendado/(?P<pk_estado>\d+)/$', views.visadores_sin_visado_agendado, name="visadores_sin_visado_agendado"),

tipos/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^tipoDocumento/new/$', views.alta_tipoDocumento),
    url(r'^tipoDocumento$', views.mostrar_tipoDocumento, name='mostrar_tipoDocumento'),
    url(r'^tipoObra/new/$', views.alta_tipoObra, name='alta_tipoObra'),
    url(r'^tipoDocumento/activar/(?P<pk_tipo_documento>\d+)/$', views.activar, name='activar_tipo_documento'),
    url(r'^tipoDocumento/desactivar/(?P<pk_tipo_documento>\d+)/$', views.desactivar, name='desactivar_tipo_documento')

]

documento/models.py
from django.db import models
from tipos.models import TipoDocumento
from tramite.models import *
from datetime import datetime

class Documento(models.Model):
    '''
    Corresponde al modelo de Documentos.
    '''
    tipo_documento = models.ForeignKey(TipoDocumento)
    #el estado va a ser momentaneamente null hasta que se agregue al tramite el documento al tramite
    tramite = models.ForeignKey(Tramite, related_name='documentos', null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='documentos/%Y/%m/%d/',null=True, blank=True)

    def __str__(self):
        return self.tipo_documento.nombre

persona/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from random import choice

class Rol(models.Model):
    '''
    Correspondiente a un rol dentro del sistema
    '''
    class Meta:
        abstract = True


class Profesional(Rol):
    '''
    Correspondiente a un rol profesional dentro del sistema
    '''
    CATEGORIAS = [
        (1, 'Categoria 1'),
        (2, 'Categoria 2'),
        (3, 'Categoria 3'),
    ]
    matricula = models.CharField(max_length=10)
    profesion = models.CharField(max_length=10)
    categoria = models.IntegerField(choices=CATEGORIAS)
    certificado = models.ImageField(upload_to='certificado/', null=True)

    def __str__(self):
        if hasattr(self, "persona"):
            return "{}".format(self.persona)
        return "Matricula: {}, Profesion: {}".format(self.matricula, self.profesion)


class Propietario(Rol):
    '''
    Correspondiente a un rol propietario dentro del sistema
    '''
    def __str__(self):
        try:
            return str(self.persona)
        except:
            return "PONEME UNA PERSONA.... ANIMAL"

    def obtener_persona(self):
        return Persona.get_self().nombre


class Usuario(Rol, AbstractUser):
    '''
    Correspondiente a un rol usuario dentro del sistema
    '''
    PROFESIONAL = "profesional"
    PROPIETARIO = "propietario"
    ADMINISTRATIVO = "administrativo"
    VISADOR = "visador"
    INSPECTOR = "inspector"
    DIRECTOR = "director"

    def get_view_name(self):
        return self.groups.first().name


    def get_view_groups(self):
        return self.groups.all()


    def pertenece_a_grupo(self, grupo):
        if self.groups.filter(name=grupo).exists():
            return True
        else:
            return False

class Persona(models.Model):
    '''
    Correspondiente al modelo de persona dentro del sistema
    '''
    SEXOS = [{'F', 'Femenino'}, {'M', 'Masculino'}]
    dni = models.IntegerField(unique=True)
    apellido = models.CharField(max_length=50)
    nombre = models.CharField(max_length=50)
    mail = models.EmailField(max_length=40)
    cuil = models.CharField(max_length=14)
    domicilio_persona = models.CharField(max_length=50)
    telefono = models.CharField(max_length=15)
    profesional = models.OneToOneField(Profesional, blank=True, null=True)
    propietario = models.OneToOneField(Propietario, blank=True, null=True)
    usuario = models.OneToOneField(Usuario, blank=True, null=True)
    perfilCSS = models.CharField(max_length=10, default="base.css")
    perfilFoto = models.ImageField(upload_to='fotoperfil/%s/', blank=True, default='fotoperfil/silueta_usuario.png')

    def __str__(self):
        return "{}, {}" .format(self.apellido, self.nombre)

    def crear_usuario(self, *extra_grupos):
        grupos = list(extra_grupos)
        created = False
        password = ""
        aux_usuario = None
        if self.usuario is None:
            password = generar_password()
            aux_usuario = Usuario.objects.create_user(username=self.mail, email=self.mail, password=password)
            created = True
        self.usuario = aux_usuario
        if self.profesional is not None:
            grupos.append(Usuario.PROFESIONAL)
        if self.propietario is not None:
            grupos.append(Usuario.PROPIETARIO)
        for nombre in grupos:
            g = Group.objects.get(name=nombre)
            self.usuario.groups.add(g)
        self.save()
        return created, password, self.usuario

    def get_profesional(self):
        return self.profesional

    def get_propietario(self):
        return self.propietario

    def modificarGrupo(self, grupo):
        for gr in self.usuario.groups.all():
            s = Group.objects.get(name=gr)
            if str(s) != "propietario" and str(s) != "profesional":
                self.usuario.groups.remove(s)
        g = Group.objects.get(name=grupo)
        self.usuario.groups.add(g)
        return self.usuario

    def modificarPerfilCSS(self, perfilseleccionado):
        self.perfilCSS = perfilseleccionado
        self.save()

    def modificarUsuario(self, mail, domicilio, telefono, imagen):
        if mail:
            self.mail = mail
        if domicilio:
            self.domicilio_persona = domicilio
        if telefono:
            self.telefono = telefono
        if imagen:
            '''self.perfilFoto.delete()'''
            self.perfilFoto = imagen
        self.save()
        return self.usuario


def generar_password():
    '''
    Funcion generar_password.
    Funcion que genera una contrasenia con valores aleatorios.
    :return password: contrasenia generada.
    '''
    longitud = 6
    valores = "123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    password = ""
    password = password.join([choice(valores) for i in range(longitud)])
    return password

persona/templates/persona/inspector/cargar_inspeccion.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags%}

{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static perfil %}">
{% endblock %}

{% block imagenusuario %}
<img src= "{{user.persona.perfilFoto.url}}" width=40 height=40 class="img-circle">
{% endblock %}

{% block barra %}
<div id="contenedor_botoncalapsable_sidebar">
    <button type="button" class="btn-collapsible-sidebar" onclick='mostrarBarra()' id="botonOn">
        <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
    </button>
</div>
<ul class="sidebar sidebar-1">
    <font size="2">
        <li><a href="javascript:history.back(-1);" class="current"><font>Inspector</font></a></li>
    </font>
</ul>
{% endblock %}

{% block contenido %}
<div id="contenedor_botoncalapsable_resto"></div>
<div class="panel-group">
	<div class="panel panel-custom">
		<div class="panel-heading panel-heading-custom box">
			<h5 class="panel-title">
				<a>
					<font color="#ffffff" size="2">Documentos del tramite</font>
				</a>
			</h5>
		</div>
		<div class="panel-collapse colorp">
			<div class="panel-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                {% for documento in tramite.documentos.all %}
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" style="height:360px;">
                                    <div class="thumbnail ">
                                        <a id="single_image" href="/media/{{documento.file}}" data-fancybox="images" data-caption="{{documento.tipo_documento}}">
                                            <img src="/media/{{documento.file}}" style="height:200px;">
                                        </a>
                                        <br>
                                        <p style="color: #17202a; font-style: oblique; text-align: center;">{{documento.tipo_documento}} - {{documento.fecha}} </p>
                                        <!--form action="">
                                            <p align="right" >
                                                <a href="#" class="btn btn-primary btn-collapsible"><i class="glyphicon glyphicon-save"></i><span>  Descargar</span></a>
                                            </p>
                                        </form-->
                                    </div>
                                </div>
                                {% endfor %}
                            <br>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    <div class="panel panel-custom">
		<div class="panel-heading panel-heading-custom box">
			<h5 class="panel-title">
				<a>
					<font color="#ffffff" size="2">Documentos de la inspección</font>
				</a>
			</h5>
		</div>
		<div class="panel-collapse colorp">
			<div class="panel-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <form  method="post" enctype="multipart/form-data">
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                    {{ctxdocumentoset}}
                                </div>
                                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                                    <div class="form-group">
                                        <label>Observaciones:</label>
                                        <input type="hidden" id="id_tramite" value="{{tramite.id}}">
                                        <input class="form-control input-sm" id="id_observaciones" name="observaciones" type="text" placeholder="Ingresar observaciones" title="Observaciones" maxlength="100" />
                                    </div>
                                <br>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" align="right">
                                    <button class="btn btn-primary btn-sm" type="submit" title="Aceptar Inspección" name="aceptar_tramite">
                                        Aprobar inspección
                                    </button>
                                    <button class="btn btn-danger btn-sm" type="submit" title="Rechazar Inspección" name="rechazar_tramite">
                                        Enviar correcciones
                                    </button>
                                </div>
                            </form>
                            <br>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
	<script>
		document.getElementById('id_boton_ayuda_2').style.visibility = 'hidden'
	</script>
    <script>
        var c = document.getElementById("botonConfiguracion");
		c.style.display= '';
		var d = document.getElementById("imagenusuario");
		d.style.display= '';
    </script>

   <script>
		$(function () {
			var cant_doc_requeridos = {{documentos_requeridos|length}};
  			for(var n = 0; n < cant_doc_requeridos; n++) {
    			var valorInput = $("input[id='id_form-"+n+"-tipo_documento']").val();
				{% for documento in documentos_requeridos %}
					var id = {{documento.id}}
					if (valorInput == id){
					    if (n == 0){
					        var valorNombreDoc = "{{documento.nombre}}" + "*: "
					    }
  						if (n > 0){
  						    var valorNombreDoc = "<br>{{documento.nombre}}</br>"
  						}
					}
				{% endfor %}
				$("label[for='id_form-"+n+"-file']").empty();
                $("label[for='id_form-"+n+"-file']").append(valorNombreDoc);
			}
		});
	</script>

    <script>
        var cant_doc_requeridos = {{ctxdocumentoset|length}};
        for(var n = 0; n < cant_doc_requeridos; n++) {
            $("input[id='id_form-"+n+"-file']").addClass('file');
            $("input[id='id_form-"+n+"-file']").attr("required", true);
        }
		$('.file').fileinput({
			showCaption: false,
			browseClass: "btn btn-primary btn-sm",
			fileType: "any",
			maxFileCount: 1,
			browseLabel: 'Seleccionar archivo',
			showUpload: false,
			showRemove: false
		});
    </script>
{% endblock %}

persona/templates/persona/inspector/documentos_tramite_inspector.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags%}

{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static perfil %}">
{% endblock %}

{% block imagenusuario %}
<img src= "{{user.persona.perfilFoto.url}}" width=40 height=40 class="img-circle">
{% endblock %}

{% block barra %}
<div id="contenedor_botoncalapsable_sidebar">
	<button type="button" class="btn-collapsible-sidebar" onclick='mostrarBarra()' id="botonOn">
		<span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
	</button>
</div>
<ul class="sidebar sidebar-1">
	<font size="2">
		<li><a href="javascript:history.back(-1);" class="current"><font>Inspector</font></a></li>
	</font>
</ul>
{% endblock %}

{% block contenido %}
<div id="contenedor_botoncalapsable_resto"></div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" >
	<div class="panel">
		<div class="panel-heading box" role="tab" id="headingFive">
			<h5 class="panel-title">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
					<font color="#ffffff" size="2">Documentos de la inspección del tramite</font>
				</a>
			</h5>
		</div>
		<div id="collapseFive" class="panel-collapse" role="tabpanel" aria-labelledby="headingFive">
			<div class="panel-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="color: white;">
							{% for documento in documentos_de_fecha %}
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" style="height:360px;">
								<div class="thumbnail ">
									<a id="single_image" href="/media/{{documento.file}}" data-fancybox="images" data-caption="{{documento.tipo_documento}}">
										<img src="/media/{{documento.file}}" style="height:200px;">
									</a>
									<br>
									<p style="color: #17202a; font-style: oblique; text-align: center;">{{documento.tipo_documento}} - {{documento.fecha}} </p>

									<!--form action="">
										<p align="right" >
											<a href="#" class="btn btn-primary btn-collapsible"><i class="glyphicon glyphicon-save"></i><span>  Descargar</span></a>
										</p>
									</form-->
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" align="right">
						<a href="javascript:history.back(-1);">
							<button type="button" class="btn btn-primary" name="Volver">
								Volver
							</button>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
	<script>
		document.getElementById('id_boton_ayuda_2').style.visibility = 'hidden'
	</script>
    <script>
		$("#id_correcciones").fileinput({
			showCaption: false,
			browseClass: "btn btn-primary btn-sm",
			fileType: "any",
			maxFileCount: 1,
			browseLabel: 'Cargar Planilla de Visado',
			showUpload: false,
			showRemove: false
		});
	</script>

    <script>
        var c = document.getElementById("botonConfiguracion");
		c.style.display= '';
		var d = document.getElementById("imagenusuario");
		d.style.display= '';
    </script>
{% endblock %}

persona/templates/persona/inspector/tramites_inspeccionados.html
{% block contenido_tramites_inspeccionados %}
<div class="table-responsive">
	<table class="table table-bordered table-striped table-hover table-condensed" style="background: white;">
		<thead>
			<tr>
				<th>Nro</th>
				<th>Fecha</th>
				<th>Tipo de obra</th>
				<th>Profesional</th>
				<th>Propietario</th>
				<th>Superficie</th>
				<th>Revisar</th>
			</tr>
		</thead>
		<tbody>
			{% if estados %}
			{% for estado in estados %}
			<tr>
				<td class="col-xs-1">{{ estado.tramite.id}}</td>
				<td class="col-xs-1">{{ estado.timestamp}}</td>
				<td class="col-xs-2">{{ estado.tramite.tipo_obra }} </td>
				<td class="col-xs-2">{{ estado.tramite.profesional}}</td>
				<td class="col-xs-2">{{ estado.tramite.propietario}}</td>
				<td class="col-xs-1">{{ estado.tramite.medidas }} </td>
				<td class="col-xs-1" align="center">
					<a href="{% url 'documentos_tramite_inspector' estado.id %}">
						<button type="button" class="btn btn-primary btn-xs" name="ver">
							<span class="glyphicon glyphicon-search" aria-hidden="true"> Documentos</span>
						</button>
					</a>
				</td>
			</tr>
			{% endfor %}
			{% endif%}
		</tbody>
	</table>
</div>
{% endblock %}