obras_particulares/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^persona/', include('persona.urls')),
    url(r'^tipos/', include('tipos.urls')),
    url(r'^tramite/', include('tramite.urls')),
    url(r'^documento/', include('documento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

persona/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from . import views
from tramite.models import *
from persona.views import *


urlpatterns = [

    #No me acuerdo de donde son - Acomodar esto!!!! -------------------------------------------------------------------

    url(r'^altapersona$', views.alta_persona, name="alta_persona"),
    url(r'^crearusuario/(?P<pk_persona>\d+)/$', views.crear_usuario, name="crear_usuario"),
    url(r'^aceptar_tramite/(?P<pk_tramite>\d+)/$', views.aceptar_tramite, name="aceptar_tramite"),

    # propietario ---------------------------------------------------------------------------------------------------
    url(r'^propietario$', views.mostrar_propietario, name="propietario"),
    url(r'^ver_historial_tramite/(?P<pk_tramite>\d+)/$', views.ver_historial_tramite, name="ver_historial_tramite"),
    url(r'^solicitud_final_obra_propietario/(?P<pk_tramite>\d+)/$', views.propietario_solicita_final_obra, name="propietario_solicita_final_obra"),
    url(r'^documentos_de_estado/(?P<pk_estado>\d+)/$', views.documentos_de_estado, name="documentos_de_estado"),
    url(r'^cargar_aprobacion_propietario/(?P<pk_tramite>\d+)/$', views.cargar_aprobacion_propietario, name="cargar_aprobacion_propietario"),
    url(r'^cargar_final_de_obra_total_propietario/(?P<pk_tramite>\d+)/$', views.cargar_final_de_obra_total_propietario, name="cargar_final_de_obra_total_propietario"),
    url(r'^cambiar_profesional_de_tramite/(?P<pk_tramite>\d+)/$', views.cambiar_profesional_de_tramite, name="cambiar_profesional_de_tramite"),

    # profesional ---------------------------------------------------------------------------------------------------
    url(r'^profesional$', views.mostrar_profesional, name="profesional"),
    url(r'^ver_documentos_tramite_profesional/(?P<pk_tramite>\d+)/$', views.ver_documentos_tramite_profesional, name="ver_documentos_tramite_profesional"),
    url(r'^ver_documentos_corregidos/(?P<pk_tramite>\d+)/$', views.ver_documentos_corregidos, name="ver_documentos_corregidos"),
    url(r'^solicitud_final_obra/(?P<pk_tramite>\d+)/$', views.profesional_solicita_final_obra, name="profesional_solicita_final_obra"),
    url(r'^solicitud_no_final_obra/(?P<pk_tramite>\d+)/$', views.profesional_solicita_no_final_obra, name="profesional_solicita_no_final_obra"),
    url(r'^solicitud_final_obra_parcial/(?P<pk_tramite>\d+)/$', views.profesional_solicita_final_obra_parcial,name="profesional_solicita_final_obra_parcial"),
    url(r'^profesional_solicita_aprobar_tramite/(?P<pk_tramite>\d+)/$', views.profesional_solicita_aprobar_tramite, name="profesional_solicita_aprobar_tramite"),
    url(r'^profesional_solicita_no_aprobar_tramite/(?P<pk_tramite>\d+)/$', views.profesional_solicita_no_aprobar_tramite,name="profesional_solicita_no_aprobar_tramite"),
    url(r'^enviar_correcciones/(?P<pk_tramite>\d+)/$', views.enviar_correcciones, name="enviar_correcciones"),
    url(r'^profesional/estado_tramite$', views.listado_tramites_de_profesional, name="estado_tramite"),
    url(r'^documento_de_estado/(?P<pk_estado>\d+)/$', views.documento_de_estado, name="documento_de_estado"),
    url(r'^cargar_final_de_obra_total_profesional/(?P<pk_tramite>\d+)/$', views.cargar_final_de_obra_total_profesional, name="cargar_final_de_obra_total_profesional"),
    url(r'^cargar_no_final_de_obra_total_profesional/(?P<pk_tramite>\d+)/$', views.cargar_no_final_de_obra_total_profesional, name="cargar_no_final_de_obra_total_profesional"),
    url(r'^cargar_no_aprobar_profesional/(?P<pk_tramite>\d+)/$', views.cargar_no_aprobar_profesional, name="cargar_no_aprobar_profesional"),

    # administrativo ------------------------------------------------------------------------------------------------
    url(r'^administrativo$', views.mostrar_administrativo, name="administrativo"),
    url(r'^crearusuario/(?P<pk_propietario>\d+)/$', views.crear_usuario, name="crear_usuario"),
    url(r'^administrativo/tramite_listar$', views.listado_de_tramites_iniciados, name="tramite_listar"),
    url(r'^ver_un_certificado/(?P<pk_persona>\d+)/$', views.ver_un_certificado, name="ver_un_certificado"),
    url(r'^documentos_tramite_administrativo/(?P<pk_tramite>\d+)/$', views.ver_documentos_tramite_administrativo, name="ver_documentos_tramite_administrativo"),
    url(r'^rechazar_tramite/(?P<pk_tramite>\d+)/$', views.rechazar_tramite, name="rechazar_tramite"),
    url(r'^aceptar_tramite/(?P<pk_tramite>\d+)/$', views.aceptar_tramite, name="aceptar_tramite"),
    url(r'^aprobar_tramite/(?P<pk_tramite>\d+)/$', views.aprobar_tramite, name="aprobar_tramite"),
    url(r'^no_aprobar_tramite/(?P<pk_tramite>\d+)/$', views.no_aprobar_tramite, name="no_aprobar_tramite"),
    url(r'^cargar_aprobacion/(?P<pk_tramite>\d+)/$', views.cargar_aprobacion, name="cargar_aprobacion"),
    url(r'^cargar_no_aprobacion/(?P<pk_tramite>\d+)/$', views.cargar_no_aprobacion, name="cargar_no_aprobacion"),
    url(r'^aprobar_final_de_obra/(?P<pk_tramite>\d+)/$', views.habilitar_final_obra, name="habilitar_final_obra"),
    url(r'^cargar_final_de_obra_total/(?P<pk_tramite>\d+)/$', views.cargar_final_de_obra_total,name="cargar_final_de_obra_total"),
    url(r'^dar_baja_tramite/(?P<pk_tramite>\d+)/$', views.dar_baja_tramite, name="dar_baja_tramite"),
    url(r'^administrativo/listado_profesionales/$', views.listado_profesionales_administrativo, name="listado_profesionales"),
    url(r'^reporte_profesionales_administrativo_excel/', ReporteProfesionalesAdministrativoExcel.as_view(), name="reporte_profesionales_administrativo_excel"),
    url(r'^administrativo/listado_propietarios/$', views.listado_propietarios_administrativo, name="listado_propietarios_administrativo"),
    url(r'^reporte_propietarios_administrativo_excel/', ReportePropietariosAdministrativoExcel.as_view(), name="reporte_propietarios_administrativo_excel"),
    url(r'^reporte_profesionales_administrativo_pdf/$', login_required(ReporteProfesionalesAdministrativoPdf.as_view()), name="reporte_profesionales_administrativo_pdf"),
    url(r'^reporte_propietarios_administrativo_pdf/$', login_required(ReportePropietariosAdministrativoPdf.as_view()), name="reporte_propietarios_administrativo_pdf"),

    # visador -------------------------------------------------------------------------------------------------------
    url(r'^visador$', views.mostrar_visador, name="visador"),
    url(r'^agendar_tramite_para_visado/(?P<pk_tramite>\d+)/$', views.agendar_tramite_para_visado, name="agendar_tramite_para_visado"),
    url(r'^ver_documentos_para_visado/(?P<pk_tramite>\d+)/$', views.ver_documentos_para_visado, name="ver_documentos_para_visado"),
    url(r'^aprobar_visado/(?P<pk_tramite>\d+)/$', views.aprobar_visado, name="aprobar_visado"),
    url(r'^no_aprobar_visado/(?P<pk_tramite>\d+)/$', views.no_aprobar_visado, name="no_aprobar_visado"),
    url(r'^ver_documentos_visados/(?P<pk_estado>\d+)/$', views.ver_documentos_visados, name="ver_documentos_visados"),

    # inspector -----------------------------------------------------------------------------------------------------
    url(r'^inspector$', views.mostrar_inspector, name="inspector"),
    url(r'^vista_de_inspecciones/(?P<pk_tramite>\d+)/$', views.ver_inspecciones, name="ver_inspecciones"),
    url(r'^cargar_inspeccion/(?P<pk_tramite>\d+)/$', views.cargar_inspeccion, name="cargar_inspeccion"),
    url(r'^agendar_tramite/(?P<pk_tramite>\d+)/$', views.agendar_tramite, name="agendar_tramite"),
    url(r'^rechazar_inspeccion/(?P<pk_tramite>\d+)/$', views.rechazar_inspeccion, name="rechazar_inspeccion"),
    url(r'^aceptar_inspeccion/(?P<pk_tramite>\d+)/$', views.aceptar_inspeccion, name="aceptar_inspeccion"),
    url(r'^documentos_tramite_inspector/(?P<pk_estado>\d+)/$', views.ver_documentos_tramite_inspector, name="documentos_tramite_inspector"),

    #jefeinspector --------------------------------------------------------------------------------------------------
    url(r'^jefeinspector$', views.mostrar_jefe_inspector, name="jefeinspector"),
    url(r'^cargar_inspeccion_final/(?P<pk_tramite>\d+)/$', views.cargar_inspeccion_final, name="cargar_inspeccion_final"),
    url(r'^agendar_inspeccion_final/(?P<pk_tramite>\d+)/$', views.agendar_inspeccion_final, name="agendar_inspeccion_final"),
    url(r'^aceptar_inspeccion_final/(?P<pk_tramite>\d+)/$', views.aceptar_inspeccion_final, name="aceptar_inspeccion_final"),
    url(r'^inspectores_sin_inspecciones_agendadas/(?P<pk_estado>\d+)/$', views.inspectores_sin_inspecciones_agendadas, name="inspectores_sin_inspecciones_agendadas"),
    url(r'^documentos_tramite_jefeinspector/(?P<pk_estado>\d+)/$', views.ver_documentos_tramite_jefeinspector, name="documentos_tramite_jefeinspector"),
    url(r'^documentos_tramite_inspector_por_jefeinspector/(?P<pk_estado>\d+)/$', views.ver_documentos_tramite_inspector_por_jefeinspector, name="documentos_tramite_inspector_por_jefeinspector"),

    #director -------------------------------------------------------------------------------------------------------
    url(r'^director$', views.mostrar_director, name="director"),
    url(r'^vista_de_tramites$', views.ver_listado_todos_tramites, name="vista_de_tramites"),
    url(r'^detalle_de_tramite/(?P<pk_tramite>\d+)/$', views.detalle_de_tramite, name="detalle_de_tramite"),
    url(r'^reporte_tramites_director_excel/', ReporteTramitesDirectorExcel.as_view(), name="reporte_tramites_director_excel"),
    url(r'^reporte_tramites_director_pdf/$', login_required(ReporteTramitesDirectorPdf.as_view()), name="reporte_tramites_director_pdf"),
    url(r'^vista_de_usuarios$', views.ver_listado_todos_usuarios, name="vista_de_usuarios"),
    url(r'^ver_actividad_usuario/(?P<usuario>\w+)/$', views.ver_actividad_usuario, name="ver_actividad_usuario"),
    url(r'^visadores_sin_visado_agendado/(?P<pk_estado>\d+)/$', views.visadores_sin_visado_agendado, name="visadores_sin_visado_agendado"),

tipos/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^tipoDocumento/new/$', views.alta_tipoDocumento),
    url(r'^tipoDocumento$', views.mostrar_tipoDocumento, name='mostrar_tipoDocumento'),
    url(r'^tipoObra/new/$', views.alta_tipoObra, name='alta_tipoObra'),
    url(r'^tipoDocumento/activar/(?P<pk_tipo_documento>\d+)/$', views.activar, name='activar_tipo_documento'),
    url(r'^tipoDocumento/desactivar/(?P<pk_tipo_documento>\d+)/$', views.desactivar, name='desactivar_tipo_documento')

]

documento/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from .models import *
from django.forms import BaseFormSet
from django.forms import formset_factory
from documento.models import *

class FormularioCorreccionesDocumento(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


class FormularioDocumento(forms.ModelForm):
    '''
    Formulario necesario para realizar la carga de los nuevos documentos.
    '''
    NAME = 'documento_form'
    SUBMIT = 'documento_submit'

    class Meta:
        model = Documento
        fields = ('tipo_documento', 'file')
        widgets = {
            'tipo_documento': forms.HiddenInput()
        }

    def save(self, commit=True, tramite=None):
        doc = super(FormularioDocumento, self).save(commit=False)
        if tramite:
            doc.tramite = tramite
        if commit:
            doc.save()
        return doc


class FormularioDocumentosSetBase(BaseFormSet):
    '''
    Fomset de formularios tipo FormularioDocumentosSetBase.
    '''
    def __init__(self, *args, **kwargs):
        super(FormularioDocumentosSetBase, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.form_tag = False


def FormularioDocumentoSetFactory(tipos):
    '''
    Funcion FormularioDocumentoSetFactory:
    Se encarga de crear una ristra de formularios de documento del tipo que reciba como parametro
    :param tipos: tipos de documento a crear
    :return: objeto Formset de documentos.
    '''
    return formset_factory(FormularioDocumento,
        formset=FormularioDocumentosSetBase,
        max_num=len(tipos), extra=len(tipos))


def metodo(tipos):
    '''
    Funcion metodo:
    Funcion que devuelve una lista de tipos de documento junto a su pk correspondiente.
    :param tipos: tipos de documento a utilizar
    :return initial: lista de tipos de documento
    '''
    initial = []
    for t in tipos:
        initial.append({'tipo_documento': t.pk})
    return initial

persona/templates/persona/profesional/cargar_final_de_obra_total.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags%}

{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static perfil %}">
{% endblock %}

{% block imagenusuario %}
<img src= "{{user.persona.perfilFoto.url}}" width=40 height=40 class="img-circle">
{% endblock %}

{% block barra %}
<div id="contenedor_botoncalapsable_sidebar">
    <button type="button" class="btn-collapsible-sidebar" onclick='mostrarBarra()' id="botonOn">
        <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
    </button>
</div>
<ul class="sidebar sidebar-1">
    <font size="2">
        <li><a href="javascript:history.back(-1);" class="current"><font>Profesional</font></a></li>
    </font>
</ul>
{% endblock %}

{% block contenido %}
<div id="contenedor_botoncalapsable_resto"></div>
<div class="panel-group">
	<div class="panel panel-custom">
		<div class="panel-heading panel-heading-custom box">
			<h5 class="panel-title">
				<a>
					<font color="#ffffff" size="2">Documentos del tramite</font>
				</a>
			</h5>
		</div>
		<div class="panel-collapse colorp">
			<div class="panel-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                {% for documento in tramite.documentos.all %}
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" style="height:360px;">
                                    <div class="thumbnail ">
                                        <a id="single_image" href="/media/{{documento.file}}" data-fancybox="images" data-caption="{{documento.tipo_documento}}">
                                            <img src="/media/{{documento.file}}" style="height:200px;">
                                        </a>
                                        <br>
                                        <p style="color: #17202a; font-style: oblique; text-align: center;">{{documento.tipo_documento}} - {{documento.fecha}} </p>
                                        <!--form action="">
                                            <p align="right" >
                                                <a href="#" class="btn btn-primary btn-collapsible"><i class="glyphicon glyphicon-save"></i><span>  Descargar</span></a>
                                            </p>
                                        </form-->
                                    </div>
                                </div>
                                {% endfor %}
                            <br>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    <div class="panel panel-custom">
		<div class="panel-heading panel-heading-custom box">
			<h5 class="panel-title">
				<a>
					<font color="#ffffff" size="2">Documentos para solicitar final de obra total del tramite</font>
				</a>
			</h5>
		</div>
		<div class="panel-collapse colorp">
			<div class="panel-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <form  method="post" enctype="multipart/form-data">
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                    {{ctxdocumentoset}}
                                </div>
                                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                                    <br>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" align="right">
                                    <button class="btn btn-primary btn-sm" type="submit" title="Aprobar_final_de_obra_total" name="aprobar_final_de_obra_total">
                                        Solicitar final de obra total
                                    </button>
                                </div>
                            </form>
                            <br>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
	<script>
		document.getElementById('id_boton_ayuda_2').style.visibility = 'hidden'
	</script>
    <script>
        var c = document.getElementById("botonConfiguracion");
		c.style.display= '';
		var d = document.getElementById("imagenusuario");
		d.style.display= '';
    </script>

   <script>
		$(function () {
			var cant_doc_requeridos = {{documentos_requeridos|length}};
  			for(var n = 0; n < cant_doc_requeridos; n++) {
    			var valorInput = $("input[id='id_form-"+n+"-tipo_documento']").val();
				{% for documento in documentos_requeridos %}
					var id = {{documento.id}}
					if (valorInput == id){
					    if (n == 0){
					        var valorNombreDoc = "{{documento.nombre}}" + "*: "
					    }
  						if (n > 0){
  						    var valorNombreDoc = "<br>{{documento.nombre}}</br>"
  						}
					}
				{% endfor %}
				$("label[for='id_form-"+n+"-file']").empty();
                $("label[for='id_form-"+n+"-file']").append(valorNombreDoc);
			}
		});
	</script>

    <script>
        var cant_doc_requeridos = {{ctxdocumentoset|length}};
        for(var n = 0; n < cant_doc_requeridos; n++) {
            $("input[id='id_form-"+n+"-file']").addClass('file');
            $("input[id='id_form-"+n+"-file']").attr("required", true);
        }
		$('.file').fileinput({
			showCaption: false,
			browseClass: "btn btn-primary btn-sm",
			fileType: "any",
			maxFileCount: 1,
			browseLabel: 'Seleccionar archivo',
			showUpload: false,
			showRemove: false
		});
    </script>
{% endblock %}

persona/templates/persona/profesional/tramites_corregidos.html
{% load staticfiles %}

{% block contenido_tramites_corregidos %}
<div class="table-responsive">
	<table  class="table table-bordered table-striped table-hover" style="background: white;">
		<thead>
			<tr>
				<th>Nro</th>
				<th>Domicilio</th>
				<th>Propietario</th>
				<th>Estado</th>
				<th>Superficie</th>
				<th>Tipo</th>
				<th>Documentos</th>
			</tr>
		</thead>
		<tbody>
			{% if tramites %}
			{% for tramite in tramites %}
			<tr>
				<td class="col-xs-1">{{tramite.id}}</td>
				<td class="col-xs-2">{{tramite.domicilio}}</td>
				<td class="col-xs-3">{{tramite.propietario}}</td>
				<td class="col-xs-2">{{tramite.estado}}</td>
				<td class="col-xs-2">{{tramite.medidas}}</td>
				<td class="col-xs-2">{{tramite.tipo_obra}}</td>
				<td align="center" class="col-xs-1">
					<a href="{% url 'ver_documentos_corregidos' tramite.pk %}">
						<button type="button" class="btn btn-primary btn-xs" name="ver_documentos_corregidos">
							<span class="glyphicon glyphicon-search" aria-hidden="true"> Ver</span>
						</button>
					</a>
				</td>
			</tr>
			{% endfor %}
			{% endif%}
		</tbody>
	</table>
</div>
{% endblock %}

persona/templates/persona/profesional/ver_documentos_corregidos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags%}

{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static perfil %}">
{% endblock %}

{% block imagenusuario %}
<img src= "{{user.persona.perfilFoto.url}}" width=40 height=40 class="img-circle">
{% endblock %}


{% block barra %}
<div id="contenedor_botoncalapsable_sidebar">
	<button type="button" class="btn-collapsible-sidebar" onclick='mostrarBarra()' id="botonOn">
		<span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
	</button>
</div>
<ul class="sidebar sidebar-1">
    <font size="2">
        <li><a href="javascript:history.back(-1);" class="current"><font>Profesional</font></a></li>
    </font>
</ul>
{% endblock %}

{% block contenido %}
<style media="screen">
	#id_file_field{
		background-color: red;
	}
</style>
<div id="contenedor_botoncalapsable_resto"></div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" >
    <div class="panel">
        <div class="panel-heading box" role="tab" id="headingFive">
            <h5 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                    <font color="#ffffff" size="2">Documentos del tramite</font>
                </a>
            </h5>
        </div>
        <div id="collapseFive" class="panel-collapse" role="tabpanel" aria-labelledby="headingFive">
            <div class="panel-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            {% for documento in tramite.documentos.all %}
                            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" style="height:360px;">
                                <div class="thumbnail">
                                    <a id="single_image" href="/media/{{documento.file}}" data-fancybox="images" data-caption="{{documento.tipo_documento}}">
                                        <img src="/media/{{documento.file}}" style="height:200px;">
                                    </a>
                                    <br>
                                    <p style="color: #17202a; font-style: oblique; text-align: center;">{{documento.tipo_documento}} - {{documento.fecha}} </p>
                                    <!--form action="">
                                        <p align="right" >
                                            <a href="#" class="btn btn-primary btn-collapsible"><i class="glyphicon glyphicon-save"></i><span>  Descargar</span></a>
                                        </p>
                                    </form-->
                                </div>
                            </div>
                            {% endfor %}
                            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                <div class="alert alert-danger alert-dismissible">
                                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                                  <strong>Atencion</strong> {{tramite.estado.observacion}}.
                                </div>
                            </div>
                        </div>
                    </div>
		    	</div>
		    </div>
	    </div>
    </div>
    <div class="panel panel-custom">
		<div class="panel-heading panel-heading-custom box">
			<h5 class="panel-title">
				<a>
					<font color="#ffffff" size="2">Documentos necesarios para realizar la corrección</font>
				</a>
			</h5>
		</div>
		<div class="panel-collapse colorp">
			<div class="panel-body">
				<div class="container-fluid">
					<div class="row">
                        <form action="" method="post" enctype="multipart/form-data">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    {{form_correcciones}}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" align="right">
                                <button class="btn btn-primary btn-sm" type="submit" title="Enviar Correcciones" name="enviar_correcciones">
                                    Enviar correcciones
                                </button>
                            <br>
                            <br>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
	<script>
		document.getElementById('id_boton_ayuda_2').style.visibility = 'hidden'
	</script>
    <script>
		$(document).ready(function() {
			$('.alert-danger').delay(999999999);
		})
	</script>
    <script>
		$(function () {
			var cant_doc_requeridos = {{documentos_requeridos|length}};
  			for(var n = 0; n < cant_doc_requeridos; n++) {
    			var valorInput = $("input[id='id_form-"+n+"-tipo_documento']").val();
				{% for documento in documentos_requeridos %}
					var id = {{documento.id}}
					if (valorInput == id){
					    if (n == 0){
					        var valorNombreDoc = "{{documento.nombre}}" + "*:"
					    }
  						if (n > 0){
  						    var valorNombreDoc = "<br>{{documento.nombre}}</br>"
  						}
					}
				{% endfor %}
				$("label[for='id_form-"+n+"-file']").empty();
                $("label[for='id_form-"+n+"-file']").append(valorNombreDoc);
			}
		});
	</script>
    <script>
        var cant_doc_requeridos = {{documentos_requeridos|length}};
        for(var n = 0; n < cant_doc_requeridos; n++) {
            $("input[id='id_form-"+n+"-file']").addClass('file');
            $("input[id='id_form-"+n+"-file']").attr("required", true);
            $("input[id='id_form-"+n+"-file']").attr("multiple", true);
        }
		$('#id_file_field').fileinput({
			showCaption: false,
			browseClass: "btn btn-primary btn-sm",
			fileType: "any",
			maxFileCount: 10,
			browseLabel: 'Seleccionar archivo',
			showUpload: false,
			showRemove: false
		});
    </script>
    <script>
      var c = document.getElementById("botonConfiguracion");
			c.style.display= '';
			var d = document.getElementById("imagenusuario");
			d.style.display= '';
    </script>
{% endblock %}